sudo: required

services:
  - docker

language: ruby
before_install:
  - docker pull ubuntu:latest
  - docker run ubuntu:latest /bin/bash &
  - docker ps
  - docker exec `docker ps | tail -1 | awk '{ print $1 }'` hostname
